# Generated by Django 5.2.9 on 2026-01-04 04:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Consulta')),
                ('hora_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('hora_fim', models.TimeField(blank=True, null=True, verbose_name='Horário de Término')),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('CONFIRMADO', 'Confirmado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado'), ('FALTA', 'Falta')], default='AGUARDANDO', max_length=20)),
            ],
            options={
                'ordering': ['data', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='O CPF deve ter exatamente 11 dígitos (apenas números).', regex='^\\d{11}$')])),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='O telefone deve ter 10 ou 11 dígitos (DDD + Número, sem traços).', regex='^\\d{10,11}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.agendamento')),
                ('evolucao', models.TextField(verbose_name='Evolução do Paciente')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='agendamento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente'),
        ),
        migrations.CreateModel(
            name='Terapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('registro_profissional', models.CharField(blank=True, max_length=50, null=True, verbose_name='CRP/CRM')),
                ('especialidade', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Login')),
            ],
        ),
        migrations.AddField(
            model_name='agendamento',
            name='terapeuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.terapeuta', verbose_name='Terapeuta Responsável'),
        ),
    ]
