# Generated by Django 5.2.9 on 2026-01-04 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_paciente_options_paciente_tipo_atendimento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={},
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='tipo_atendimento',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='O CPF deve ter exatamente 11 dígitos (apenas números).', regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='O telefone deve ter 10 ou 11 dígitos (DDD + Número, sem traços).', regex='^\\d{10,11}$')]),
        ),
    ]
