# Generated by Django 5.2.9 on 2026-01-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_paciente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='tipo_atendimento',
            field=models.CharField(choices=[('PARTICULAR', 'Particular'), ('DESCONTO', 'Particular com Desconto'), ('CONVENIO', 'Convênio'), ('SOCIAL', 'Social')], default='PARTICULAR', max_length=20, verbose_name='Tipo (Nesta consulta)'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_padrao',
            field=models.CharField(choices=[('PARTICULAR', 'Particular'), ('DESCONTO', 'Particular com Desconto'), ('CONVENIO', 'Convênio'), ('SOCIAL', 'Social')], default='PARTICULAR', max_length=20, verbose_name='Tipo de Atendimento Padrão'),
        ),
    ]
