# Generated by Django 5.2.9 on 2026-01-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_agendamento_deletado_alter_agendamento_terapeuta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado'), ('FALTA', 'Falta')], default='AGUARDANDO', max_length=20),
        ),
    ]
