# Generated by Django 5.2.9 on 2026-01-06 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_paciente_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve ter 11 dígitos.', regex='^\\d{11}$')]),
        ),
    ]
