# Generated by Django 5.2.9 on 2026-01-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_paciente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='deletado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tipo_atendimento',
            field=models.CharField(choices=[('PARTICULAR', 'Particular'), ('DESCONTO', 'Particular com Desconto'), ('CONVENIO', 'Convênio'), ('SOCIAL', 'Social')], default='PARTICULAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
