# Generated by Django 5.2.9 on 2026-01-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_agendamento_deletado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Cadastro Ativo'),
        ),
    ]
