# Generated by Django 5.2.9 on 2026-01-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_terapeuta_especialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terapeuta',
            name='especialidade',
            field=models.CharField(blank=True, choices=[('Fonoaudiólogo(a)', 'Fonoaudiólogo(a)'), ('Fisioterapeuta', 'Fisioterapeuta'), ('Terapeuta Ocupacional', 'Terapeuta Ocupacional'), ('Psicólogo(a)', 'Psicólogo(a)'), ('Psicomotricista', 'Psicomotricista'), ('Nutricionista', 'Nutricionista'), ('Psicopedagogo(a)', 'Psicopedagogo(a)'), ('Musicoterapeuta', 'Musicoterapeuta'), ('Arteterapeuta', 'Arteterapeuta'), ('Terapeuta Alimentar', 'Terapeuta Alimentar')], max_length=50, null=True),
        ),
    ]
