# Generated by Django 5.2.9 on 2026-01-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_terapeuta_especialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('REALIZADO', 'Realizado'), ('FALTA', 'Falta')], default='AGUARDANDO', max_length=20),
        ),
    ]
