# Generated by Django 5.2.9 on 2026-01-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_agendamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True, verbose_name='Observação da Falta'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='tipo_cancelamento',
            field=models.CharField(blank=True, choices=[('JUSTIFICADA', 'Falta Justificada'), ('NAO_JUSTIFICADA', 'Falta Não Justificada'), ('NAO_LIBERACAO', 'Não Liberação (Convênio)'), ('TERAPEUTA', 'Falta do Terapeuta')], max_length=20, null=True, verbose_name='Tipo de Falta'),
        ),
    ]
