# Generated by Django 5.2.9 on 2026-01-15 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_agendamento_motivo_cancelamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='prontuarios/%Y/%m/', verbose_name='Arquivo')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.consulta')),
            ],
        ),
    ]
