# Generated by Django 5.2.9 on 2026-01-15 19:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_anexoconsulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexoconsulta',
            name='arquivo',
            field=models.FileField(upload_to='prontuarios/%Y/%m/', validators=[core.models.validar_tamanho_arquivo], verbose_name='Arquivo'),
        ),
    ]
