# Generated by Django 5.2.9 on 2026-01-15 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_anexoconsulta_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Convênio')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Convênio',
                'verbose_name_plural': 'Convênios',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='carteirinha',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Carteirinha'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.convenio', verbose_name='Convênio (Se houver)'),
        ),
    ]
