# Generated by Django 5.2.9 on 2026-01-16 13:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_convenio_paciente_carteirinha_paciente_convenio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Sala')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaFixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da Semana')),
                ('hora_inicio', models.TimeField(verbose_name='Início')),
                ('hora_fim', models.TimeField(verbose_name='Fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='Grade Ativa')),
                ('data_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Vigência Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Vigência Fim (Opcional)')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.terapeuta')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sala', verbose_name='Sala Fixa')),
            ],
            options={
                'verbose_name': 'Horário Fixo (Grade)',
                'verbose_name_plural': 'Agenda Fixa (Grade)',
            },
        ),
        migrations.AddField(
            model_name='agendamento',
            name='agenda_fixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_gerados', to='core.agendafixa'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sala'),
        ),
    ]
