# Generated by Django 5.2.9 on 2026-01-16 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_sala_agendafixa_agendamento_agenda_fixa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendafixa',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.sala', verbose_name='Sala Fixa'),
        ),
    ]
