# Generated by Django 5.2.9 on 2026-01-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_agendafixa_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='nome_search',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
