# Generated by Django 5.2.9 on 2026-01-22 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_paciente_nome_search'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terapeuta',
            options={'ordering': ['nome']},
        ),
    ]
