# Generated by Django 5.2.9 on 2026-01-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_terapeuta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendafixa',
            name='modalidade',
            field=models.CharField(choices=[('FISIOTERAPIA', 'Fisioterapia (Convencional)'), ('BOBATH', 'Fisioterapia (Bobath)'), ('PEDIA', 'Fisioterapia (Pedia)'), ('AT', 'Assistente Terapêutico (AT)'), ('FONOAUDIOLOGIA', 'Fonoaudiologia'), ('PSICOLOGIA', 'Psicologia'), ('TO', 'Terapeuta Ocupacional'), ('PSICOMOTRICIDADE', 'Psicomotricidade'), ('NUTRICAO', 'Nutrição'), ('PSICOPEDAGOGIA', 'Psicopedagogia'), ('MUSICOTERAPIA', 'Musicoterapia'), ('ARTETERAPIA', 'Arteterapeuta'), ('TERAPIA_ALIMENTAR', 'Terapia Alimentar')], default='FISIOTERAPIA', max_length=50, verbose_name='Especialidade/Modalidade'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='modalidade',
            field=models.CharField(choices=[('FISIOTERAPIA', 'Fisioterapia (Convencional)'), ('BOBATH', 'Fisioterapia (Bobath)'), ('PEDIA', 'Fisioterapia (Pedia)'), ('AT', 'Assistente Terapêutico (AT)'), ('FONOAUDIOLOGIA', 'Fonoaudiologia'), ('PSICOLOGIA', 'Psicologia'), ('TO', 'Terapeuta Ocupacional'), ('PSICOMOTRICIDADE', 'Psicomotricidade'), ('NUTRICAO', 'Nutrição'), ('PSICOPEDAGOGIA', 'Psicopedagogia'), ('MUSICOTERAPIA', 'Musicoterapia'), ('ARTETERAPIA', 'Arteterapeuta'), ('TERAPIA_ALIMENTAR', 'Terapia Alimentar')], default='FISIOTERAPIA', max_length=50, verbose_name='Modalidade (Nesta Consulta)'),
        ),
    ]
