# Generated by Django 5.2.9 on 2026-01-22 14:54

import core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_agendafixa_modalidade_agendamento_modalidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['nome'], 'verbose_name': 'Paciente'},
        ),
        migrations.AlterField(
            model_name='agendafixa',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='agendafixa',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendafixa',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='agendafixa',
            name='dia_semana',
            field=models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')]),
        ),
        migrations.AlterField(
            model_name='agendafixa',
            name='hora_fim',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='agendafixa',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='agendafixa',
            name='modalidade',
            field=models.CharField(blank=True, choices=[('BOBATH', 'Fisioterapia (Bobath)'), ('PEDIA', 'Fisioterapia (Pedia)'), ('AT', 'Assistente Terapêutico (AT)')], default=None, max_length=50, null=True, verbose_name='Modalidade (Vazio = Padrão)'),
        ),
        migrations.AlterField(
            model_name='agendafixa',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.sala'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='modalidade',
            field=models.CharField(blank=True, choices=[('BOBATH', 'Fisioterapia (Bobath)'), ('PEDIA', 'Fisioterapia (Pedia)'), ('AT', 'Assistente Terapêutico (AT)')], default=None, max_length=50, null=True, verbose_name='Modalidade (Consulta)'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tipo_cancelamento',
            field=models.CharField(blank=True, choices=[('JUSTIFICADA', 'Falta Justificada'), ('NAO_JUSTIFICADA', 'Falta Não Justificada'), ('NAO_LIBERACAO', 'Não Liberação (Convênio)'), ('TERAPEUTA', 'Falta do Terapeuta')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='anexoconsulta',
            name='arquivo',
            field=models.FileField(upload_to='prontuarios/%Y/%m/', validators=[core.models.validar_tamanho_arquivo]),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='evolucao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='carteirinha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.convenio'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{10,11}$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_padrao',
            field=models.CharField(choices=[('PARTICULAR', 'Particular'), ('DESCONTO', 'Particular com Desconto'), ('CONVENIO', 'Convênio'), ('SOCIAL', 'Social')], default='PARTICULAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='terapeuta',
            name='especialidade',
            field=models.CharField(blank=True, choices=[('Fonoaudiólogo(a)', 'Fonoaudiólogo(a)'), ('Fisioterapeuta', 'Fisioterapeuta'), ('Terapeuta Ocupacional', 'Terapeuta Ocupacional'), ('Psicólogo(a)', 'Psicólogo(a)'), ('Psicomotricista', 'Psicomotricista'), ('Nutricionista', 'Nutricionista'), ('Psicopedagogo(a)', 'Psicopedagogo(a)'), ('Musicoterapeuta', 'Musicoterapeuta'), ('Arteterapeuta', 'Arteterapeuta'), ('Terapeuta Alimentar', 'Terapeuta Alimentar'), ('Assistente Terapêutico', 'Assistente Terapêutico')], max_length=50, null=True),
        ),
    ]
