# Generated by Django 5.2.9 on 2026-01-22 15:14

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_paciente_options_alter_agendafixa_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendafixa',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Grade Ativa'),
        ),
        migrations.AlterField(
            model_name='agendafixa',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Vigência Fim (Opcional)'),
        ),
        migrations.AlterField(
            model_name='agendafixa',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Vigência Início'),
        ),
        migrations.AlterField(
            model_name='agendafixa',
            name='dia_semana',
            field=models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da Semana'),
        ),
        migrations.AlterField(
            model_name='agendafixa',
            name='hora_fim',
            field=models.TimeField(verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='agendafixa',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='agendafixa',
            name='modalidade',
            field=models.CharField(blank=True, choices=[('BOBATH', 'Fisioterapia (Bobath)'), ('PEDIASUIT', 'Fisioterapia (Pediasuit)'), ('RESPIRATORIA', 'Fisioterapia (Respiratória)'), ('AT', 'Assistente Terapêutico (AT)'), ('PSICOPEDAGOGIA', 'Psicopedagogia')], default=None, max_length=50, null=True, verbose_name='Modalidade (Vazio = Padrão)'),
        ),
        migrations.AlterField(
            model_name='agendafixa',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.sala', verbose_name='Sala Fixa'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(verbose_name='Data da Consulta'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Término'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Horário de Início'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='modalidade',
            field=models.CharField(blank=True, choices=[('BOBATH', 'Fisioterapia (Bobath)'), ('PEDIASUIT', 'Fisioterapia (Pediasuit)'), ('RESPIRATORIA', 'Fisioterapia (Respiratória)'), ('AT', 'Assistente Terapêutico (AT)'), ('PSICOPEDAGOGIA', 'Psicopedagogia')], default=None, max_length=50, null=True, verbose_name='Modalidade (Consulta)'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True, verbose_name='Observação da Falta'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tipo_cancelamento',
            field=models.CharField(blank=True, choices=[('JUSTIFICADA', 'Falta Justificada'), ('NAO_JUSTIFICADA', 'Falta Não Justificada'), ('NAO_LIBERACAO', 'Não Liberação (Convênio)'), ('TERAPEUTA', 'Falta do Terapeuta')], max_length=20, null=True, verbose_name='Tipo de Falta'),
        ),
        migrations.AlterField(
            model_name='anexoconsulta',
            name='arquivo',
            field=models.FileField(upload_to='prontuarios/%Y/%m/', validators=[core.models.validar_tamanho_arquivo], verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='evolucao',
            field=models.TextField(verbose_name='Evolução do Paciente'),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Cadastro Ativo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='carteirinha',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Carteirinha'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.convenio', verbose_name='Convênio (Se houver)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_padrao',
            field=models.CharField(choices=[('PARTICULAR', 'Particular'), ('DESCONTO', 'Particular com Desconto'), ('CONVENIO', 'Convênio'), ('SOCIAL', 'Social')], default='PARTICULAR', max_length=20, verbose_name='Tipo de Atendimento Padrão'),
        ),
    ]
