# Generated by Django 5.2.9 on 2026-01-30 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_paciente_options_alter_paciente_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueioAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('motivo', models.CharField(blank=True, default='Indisponível', max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.terapeuta')),
            ],
        ),
    ]
