# Generated by Django 5.2.9 on 2026-01-30 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_bloqueioagenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueioFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da Semana')),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('motivo', models.CharField(blank=True, default='Bloqueio Fixo', max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.terapeuta')),
            ],
            options={
                'verbose_name': 'Bloqueio de Agenda (Fixo)',
                'verbose_name_plural': 'Bloqueios de Agenda (Fixos)',
            },
        ),
        migrations.DeleteModel(
            name='BloqueioAgenda',
        ),
    ]
