# Generated by Django 5.2.9 on 2026-01-30 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_bloqueiofixo_delete_bloqueioagenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloqueiofixo',
            name='motivo',
        ),
    ]
