# Generated by Django 5.2.9 on 2026-04-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_bloqueiosala'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='autorizacao_imagem',
            field=models.CharField(choices=[('NAO_PREENCHIDO', 'Não preenchido'), ('AUTORIZADO', 'Autorizado'), ('NAO_AUTORIZADO', 'Não autorizado')], default='NAO_PREENCHIDO', max_length=20, verbose_name='Autorização de Uso de Imagem'),
        ),
    ]
