# Generated by Django 5.2.9 on 2026-06-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_paciente_autorizacao_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendafixa',
            name='modalidade',
            field=models.CharField(blank=True, choices=[('BOBATH', 'Fisioterapia (Bobath)'), ('PEDIASUIT', 'Fisioterapia (Pediasuit)'), ('RESPIRATORIA', 'Fisioterapia (Respiratória)'), ('AT', 'Assistente Terapêutico (AT)'), ('PSICOPEDAGOGIA', 'Psicopedagogia'), ('coordenacao', 'Coordenação')], default=None, max_length=50, null=True, verbose_name='Modalidade (Vazio = Padrão)'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='modalidade',
            field=models.CharField(blank=True, choices=[('BOBATH', 'Fisioterapia (Bobath)'), ('PEDIASUIT', 'Fisioterapia (Pediasuit)'), ('RESPIRATORIA', 'Fisioterapia (Respiratória)'), ('AT', 'Assistente Terapêutico (AT)'), ('PSICOPEDAGOGIA', 'Psicopedagogia'), ('coordenacao', 'Coordenação')], default=None, max_length=50, null=True, verbose_name='Modalidade (Consulta)'),
        ),
    ]
