# Generated by Django 5.2.9 on 2026-08-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_agendafixa_modalidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terapeuta',
            name='coordenacao',
            field=models.BooleanField(default=False, verbose_name='É Coordenação'),
        ),
        migrations.AlterField(
            model_name='terapeuta',
            name='especialidade',
            field=models.CharField(blank=True, choices=[('Fonoaudiólogo(a)', 'Fonoaudiólogo(a)'), ('Fisioterapeuta', 'Fisioterapeuta'), ('Terapeuta Ocupacional', 'Terapeuta Ocupacional'), ('Psicólogo(a)', 'Psicólogo(a)'), ('Psicomotricista', 'Psicomotricista'), ('Nutricionista', 'Nutricionista'), ('Psicopedagogo(a)', 'Psicopedagogo(a)'), ('Musicoterapeuta', 'Musicoterapeuta'), ('Arteterapeuta', 'Arteterapeuta'), ('Terapeuta Alimentar', 'Terapeuta Alimentar'), ('Assistente Terapêutico', 'Assistente Terapêutico'), ('Coordenação', 'Coordenação')], max_length=50, null=True),
        ),
    ]
